### ISSUE TITLE
module `gonum.org/v1/plot.New()` function signature mismatch 

### ISSUE THREAD

**Issue by soypat** [milosgajdos/go-estimate#7]
```log
myproject/vendor/github.com/milosgajdos/go-estimate/sim/plot.go:35:9: assignment mismatch: 2 variables but plot.New returns 1 values
myproject/vendor/github.com/milosgajdos/go-estimate/sim/plot.go:43:14: assignment mismatch: 2 variables but plot.NewLegend returns 1 values
```
Link to file https://github.com/milosgajdos/go-estimate/blob/master/sim/plot.go#L35

Running `go mod tidy` does not fix it. I'm on `go version go1.16.3 linux/amd64`.

**Comment by milosgajdos** [comment]
Strange. I'm on the same version of `Go` and everything seems to work just fine:
```
$ go version
go version go1.16.3 darwin/amd64
$ go get ./...
$ go build ./...
```

Note, this project pins `gonum/plot` to the following [commit](https://github.com/gonum/plot/commits/e2840ee46a6b612972d746f9fea9920d329a0605). If you browse the `plot` module code tree pointing to this commit you'll discover that `plot.New()` indeed returns 2 values see [here](https://github.com/gonum/plot/blob/e2840ee46a6b612972d746f9fea9920d329a0605/plot.go#L79) which makes me think you must've gotten your dependencies upgraded somehow.

Please remove your build cache and make sure you get the right dependencies by running `make dep`.

**Comment by milosgajdos** [comment]
Closing as per https://github.com/milosgajdos/go-estimate/pull/9#issuecomment-850848571
